### ISSUE TITLE
Niewielki problem

### ISSUE THREAD

**Issue by fhodun** [fhodun/testshots#1]
Jeżeli użyjemy screenshotowania więcej niż raz na tej samej aktywnej sesji program się psuje i wyskakuje błąd:
```
Traceback (most recent call last):
  File "C:\Users\filip\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\filip\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\filip\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=65379): Max retries exceeded with url: /session/c8fdd5bf844342d110623ce96cabe54a/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000258E2AC0340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```

**Comment by fhodun** [comment]
Naprawione
